# source 'git@github.com:gabrielar/GDRSPods.git'


target 'GDRSImageCacheTestProjectTests' do
    pod 'GDRSImageCache', :path => '..'
    # pod 'GDRSImageCache', '~> 1.0.1'
end

target 'GDRSImageCacheTestProjectVisualTests' do
    pod 'GDRSImageCache', :path => '..'
    # pod 'GDRSImageCache', '~> 1.0.1'
end

